<a href="https://colab.research.google.com/github/PravinV001/Python/blob/Class_N_Colab/Numpy_in_Detail.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Extracting numeric data as NumPy arrays for future analysis
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])

print("Votes (Array):", votes)
print("Costs (Array):", costs)

Votes (Array): [ 775  787  918   88  166  286 2556  324  504  402]
Costs (Array): ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]


In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
costs

array(["'800.0'", "'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'",
       "'600.0'", "'700.0'", "'550.0'", "'500.0'"], dtype='<U7')

In [ ]:
costs_2= np.char.replace(costs, "'",'')

In [ ]:
costs_cleaned= costs_2.astype(float)

In [ ]:
costs_cleaned

array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])

In [ ]:
mixed_data= np.array([100,'200', 300.5, 'Hundred'])

In [ ]:
mixed_data #unicode string

array(['100', '200', '300.5', 'Hundred'], dtype='<U32')

In [ ]:
mixed_data[2]

np.str_('300.5')

In [ ]:
mixed_data[-1]

np.str_('Hundred')

In [ ]:
#sample of 50 restaurants

sample_votes = np.array([775, 787, 918, 88, 166, 286, 2556, 324, 504, 402, 150, 164, 424, 918, 90, 133, 144, 93, 62, 180, 62, 148, 219, 506, 172, 415, 230, 1647, 4884, 133, 286, 540, 2556, 36, 244, 804, 679, 245, 345, 618, 1047, 627, 354, 244, 163, 808, 1720, 868, 520, 299])
sample_costs = np.array([800.0, 800.0, 800.0, 300.0, 600.0, 600.0, 600.0, 700.0, 550.0, 500.0, 600.0, 500.0, 450.0, 800.0, 650.0, 800.0, 700.0, 300.0, 400.0, 500.0, 600.0, 550.0, 600.0, 500.0, 750.0, 500.0, 650.0, 600.0, 750.0, 200.0, 500.0, 800.0, 600.0, 400.0, 300.0, 450.0, 850.0, 300.0, 400.0, 750.0, 450.0, 450.0, 800.0, 800.0, 800.0, 850.0, 400.0, 1200.0, 300.0, 300.0])


In [ ]:
restaurants_data= np.column_stack((sample_votes, sample_costs))

In [ ]:
restaurants_data.ndim

2

In [ ]:
restaurants_data

array([[ 775.,  800.],
       [ 787.,  800.],
       [ 918.,  800.],
       [  88.,  300.],
       [ 166.,  600.],
       [ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 402.,  500.],
       [ 150.,  600.],
       [ 164.,  500.],
       [ 424.,  450.],
       [ 918.,  800.],
       [  90.,  650.],
       [ 133.,  800.],
       [ 144.,  700.],
       [  93.,  300.],
       [  62.,  400.],
       [ 180.,  500.],
       [  62.,  600.],
       [ 148.,  550.],
       [ 219.,  600.],
       [ 506.,  500.],
       [ 172.,  750.],
       [ 415.,  500.],
       [ 230.,  650.],
       [1647.,  600.],
       [4884.,  750.],
       [ 133.,  200.],
       [ 286.,  500.],
       [ 540.,  800.],
       [2556.,  600.],
       [  36.,  400.],
       [ 244.,  300.],
       [ 804.,  450.],
       [ 679.,  850.],
       [ 245.,  300.],
       [ 345.,  400.],
       [ 618.,  750.],
       [1047.,  450.],
       [ 627.,  450.],
       [ 354.,  800.],
       [ 24

In [ ]:
#from 2d to 4d
restaurants_data.reshape (25,4)


array([[ 775.,  800.,  787.,  800.],
       [ 918.,  800.,   88.,  300.],
       [ 166.,  600.,  286.,  600.],
       [2556.,  600.,  324.,  700.],
       [ 504.,  550.,  402.,  500.],
       [ 150.,  600.,  164.,  500.],
       [ 424.,  450.,  918.,  800.],
       [  90.,  650.,  133.,  800.],
       [ 144.,  700.,   93.,  300.],
       [  62.,  400.,  180.,  500.],
       [  62.,  600.,  148.,  550.],
       [ 219.,  600.,  506.,  500.],
       [ 172.,  750.,  415.,  500.],
       [ 230.,  650., 1647.,  600.],
       [4884.,  750.,  133.,  200.],
       [ 286.,  500.,  540.,  800.],
       [2556.,  600.,   36.,  400.],
       [ 244.,  300.,  804.,  450.],
       [ 679.,  850.,  245.,  300.],
       [ 345.,  400.,  618.,  750.],
       [1047.,  450.,  627.,  450.],
       [ 354.,  800.,  244.,  800.],
       [ 163.,  800.,  808.,  850.],
       [1720.,  400.,  868., 1200.],
       [ 520.,  300.,  299.,  300.]])

In [ ]:
restaurants_data.reshape (10,10)

array([[ 775.,  800.,  787.,  800.,  918.,  800.,   88.,  300.,  166.,
         600.],
       [ 286.,  600., 2556.,  600.,  324.,  700.,  504.,  550.,  402.,
         500.],
       [ 150.,  600.,  164.,  500.,  424.,  450.,  918.,  800.,   90.,
         650.],
       [ 133.,  800.,  144.,  700.,   93.,  300.,   62.,  400.,  180.,
         500.],
       [  62.,  600.,  148.,  550.,  219.,  600.,  506.,  500.,  172.,
         750.],
       [ 415.,  500.,  230.,  650., 1647.,  600., 4884.,  750.,  133.,
         200.],
       [ 286.,  500.,  540.,  800., 2556.,  600.,   36.,  400.,  244.,
         300.],
       [ 804.,  450.,  679.,  850.,  245.,  300.,  345.,  400.,  618.,
         750.],
       [1047.,  450.,  627.,  450.,  354.,  800.,  244.,  800.,  163.,
         800.],
       [ 808.,  850., 1720.,  400.,  868., 1200.,  520.,  300.,  299.,
         300.]])

In [ ]:
restaurants_data[:10]

array([[ 775.,  800.],
       [ 787.,  800.],
       [ 918.,  800.],
       [  88.,  300.],
       [ 166.,  600.],
       [ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 402.,  500.]])

In [ ]:
restaurants_data[:10].T

array([[ 775.,  787.,  918.,   88.,  166.,  286., 2556.,  324.,  504.,
         402.],
       [ 800.,  800.,  800.,  300.,  600.,  600.,  600.,  700.,  550.,
         500.]])

In [ ]:
restaurants_data[:10]

array([[ 775.,  800.],
       [ 787.,  800.],
       [ 918.,  800.],
       [  88.,  300.],
       [ 166.,  600.],
       [ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 402.,  500.]])

In [ ]:
restaurants_data[:10,0] #which column to fetch is 0

array([ 775.,  787.,  918.,   88.,  166.,  286., 2556.,  324.,  504.,
        402.])

In [ ]:
restaurants_data[:10,1]

array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])

In [ ]:
#extraction from 2D AND CREATING A 1 D ARRAY
all_votes=restaurants_data[:,0]
all_cost= restaurants_data[:,1]

In [ ]:
all_votes

array([ 775.,  787.,  918.,   88.,  166.,  286., 2556.,  324.,  504.,
        402.,  150.,  164.,  424.,  918.,   90.,  133.,  144.,   93.,
         62.,  180.,   62.,  148.,  219.,  506.,  172.,  415.,  230.,
       1647., 4884.,  133.,  286.,  540., 2556.,   36.,  244.,  804.,
        679.,  245.,  345.,  618., 1047.,  627.,  354.,  244.,  163.,
        808., 1720.,  868.,  520.,  299.])

In [ ]:
#SUM - NUMPY WAY OF DOING THE SUM -- faster sum

print(np.sum(all_votes))

30583.0


In [ ]:
print(np.mean(all_votes))

611.66


In [ ]:
print(np.min(all_votes))

36.0


In [ ]:
print(np.max(all_votes))

4884.0


In [ ]:
#arange
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
data= np.arange(12).reshape(3,4)

In [ ]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#rows axis =0
#columns axis =1


np.sum(data, axis =0)

array([12, 15, 18, 21])

In [ ]:
np.sum(data, axis =1)

array([ 6, 22, 38])

In [ ]:
#filtering tasks

all_cost


array([ 800.,  800.,  800.,  300.,  600.,  600.,  600.,  700.,  550.,
        500.,  600.,  500.,  450.,  800.,  650.,  800.,  700.,  300.,
        400.,  500.,  600.,  550.,  600.,  500.,  750.,  500.,  650.,
        600.,  750.,  200.,  500.,  800.,  600.,  400.,  300.,  450.,
        850.,  300.,  400.,  750.,  450.,  450.,  800.,  800.,  800.,
        850.,  400., 1200.,  300.,  300.])

In [ ]:
np.where (all_cost >500)

(array([ 0,  1,  2,  4,  5,  6,  7,  8, 10, 13, 14, 15, 16, 20, 21, 22, 24,
        26, 27, 28, 31, 32, 36, 39, 42, 43, 44, 45, 47]),)

In [ ]:
all_cost[np.where (all_cost >500)].size

29

In [ ]:
#are there any restaurants with cost greater than 3000

In [ ]:
print(np.any(all_cost>3000))

False


In [ ]:
# are all restaurants cheaper than 5000

print(np.all(all_cost <5000))

True


In [ ]:
all_cost[np.where(all_cost <5000)].size == all_cost.size

True

In [ ]:
##### 2D ######

numeric_data = np.array([
    [4.1, 775.0, 800.0],
    [3.8, 787.0, 800.0],
    [4.0, 918.0, 800.0],
    [2.6, 88.0, 300.0],
    [1.1, 166.0, 600.0],
    [3.5, 286.0, 600.0],
    [4.7, 2556.0, 600.0],
    [2.5, 324.0, 700.0],
    [2.8, 504.0, 550.0],
    [3.4, 402.0, 500.0]
])

# Just to display in a good way
# Set print options to suppress scientific notation
np.set_printoptions(suppress=True, precision=1)

# Print the array
print("Numeric data (formatted):")
print(numeric_data)

Numeric data (formatted):
[[   4.1  775.   800. ]
 [   3.8  787.   800. ]
 [   4.   918.   800. ]
 [   2.6   88.   300. ]
 [   1.1  166.   600. ]
 [   3.5  286.   600. ]
 [   4.7 2556.   600. ]
 [   2.5  324.   700. ]
 [   2.8  504.   550. ]
 [   3.4  402.   500. ]]


In [ ]:
#SORT IN ASCENDING ORDER ALONG THE ROWS

np.sort(numeric_data, axis=0)

array([[   1.1,   88. ,  300. ],
       [   2.5,  166. ,  500. ],
       [   2.6,  286. ,  550. ],
       [   2.8,  324. ,  600. ],
       [   3.4,  402. ,  600. ],
       [   3.5,  504. ,  600. ],
       [   3.8,  775. ,  700. ],
       [   4. ,  787. ,  800. ],
       [   4.1,  918. ,  800. ],
       [   4.7, 2556. ,  800. ]])

In [ ]:
ratings = numeric_data[:,0]

In [ ]:
ratings

array([4.1, 3.8, 4. , 2.6, 1.1, 3.5, 4.7, 2.5, 2.8, 3.4])

In [ ]:
#indices when sorting

np.argsort(ratings)

array([4, 7, 3, 8, 9, 5, 1, 2, 0, 6])

In [ ]:
#give me the index of ther max value
print(np.argmax(ratings))

6


In [ ]:
#power of numpy


x = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [ ]:
y= np.arange (3,12).reshape(3,3)

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
x@ y

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [ ]:
np.matmul(x,y)

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [ ]:
np.dot(x,y)

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [ ]:
#

def discount_cost(rate, cost):
    """Apply a 10% discount if the rating is 4.0 or higher."""
    if rate >= 4.0:
        return cost * 0.9
    else:
        return cost

In [ ]:
rating = numeric_data[:, 0]
cost = numeric_data[:, 1]

In [ ]:
vectorized_discount_cost = np.vectorize(discount_cost)

In [ ]:
vectorized_discount_cost(rating, cost)

array([ 697.5,  787. ,  826.2,   88. ,  166. ,  286. , 2300.4,  324. ,
        504. ,  402. ])