<a href="https://colab.research.google.com/github/PravinV001/Python/blob/Class_N_Colab/Zomato_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Extracting numeric data as NumPy arrays for future analysis
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])

print("Votes (Array):", votes)
print("Costs (Array):", costs)

Votes (Array): [ 775  787  918   88  166  286 2556  324  504  402]
Costs (Array): ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]


In [ ]:


import numpy as np

large_list = list(range (1000000))

large_array = np.arange(1000000)



In [ ]:
large_array

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
import time
start = time.time()

#operation done on a python list
sum_list = sum(large_list)


end = time.time()

list_time = end - start

print(list_time)

0.02013397216796875


In [ ]:
import time
start = time.time()

#operation done on a python list
sum_numpy = np.sum(large_array)


end = time.time()

numpy_time = end - start

print(numpy_time)

0.0013015270233154297


In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
costs

array(["'800.0'", "'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'",
       "'600.0'", "'700.0'", "'550.0'", "'500.0'"], dtype='<U7')

In [ ]:
#characteristics

votes.shape


(10,)

In [ ]:
votes.ndim

1

In [ ]:
votes.size

10

In [ ]:
costs.ndim

1

In [ ]:
#2D Data

suraaj_matrix= np.array([votes, costs]).T

In [ ]:
suraaj_matrix

array([['775', "'800.0'"],
       ['787', "'800.0'"],
       ['918', "'800.0'"],
       ['88', "'300.0'"],
       ['166', "'600.0'"],
       ['286', "'600.0'"],
       ['2556', "'600.0'"],
       ['324', "'700.0'"],
       ['504', "'550.0'"],
       ['402', "'500.0'"]], dtype='<U21')

In [ ]:
suraaj_matrix.ndim

2

In [ ]:
suraaj_matrix.shape

(10, 2)

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [ ]:
costs

array(["'800.0'", "'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'",
       "'600.0'", "'700.0'", "'550.0'", "'500.0'"], dtype='<U7')

In [ ]:
costs.dtype

dtype('<U7')

In [ ]:
costs_1= np.char.replace(costs, ',','')

In [ ]:
costs_2= np.char.replace(costs, "'",'')

In [ ]:
costs_2

array(['800.0', '800.0', '800.0', '300.0', '600.0', '600.0', '600.0',
       '700.0', '550.0', '500.0'], dtype='<U5')

In [ ]:
costs_2.dtype

dtype('<U5')

In [ ]:
costs_cleaned= costs_2.astype(float)

In [ ]:
costs_cleaned[0]

np.float64(800.0)

In [ ]:
costs_cleaned

array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])

In [ ]:
costs_cleaned[1]

np.float64(800.0)

In [ ]:
costs_cleaned[3]

np.float64(300.0)

In [ ]:
costs_cleaned[-1]

np.float64(500.0)

In [ ]:
costs_cleaned[[1,3,-1]]

array([800., 300., 500.])

In [ ]:
costs_cleaned[0:4]

array([800., 800., 800., 300.])

In [ ]:
costs_cleaned[:4]

array([800., 800., 800., 300.])

In [ ]:
#MASKING

costs_cleaned < 500

array([False, False, False,  True, False, False, False, False, False,
       False])

In [ ]:
costs_cleaned

array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])

In [ ]:
#activity

my_list= [1,2,3,4,5,6,7]

new_list=[]

for i in my_list:
    new_list.append(i * 2)

print(new_list)



[2, 4, 6, 8, 10, 12, 14]


In [ ]:
my_list_new= np.array ([1,2,3,4,5,6,7])


In [ ]:
my_list_new * 2

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
my_list * 2

[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
costs_cleaned < 500

array([False, False, False,  True, False, False, False, False, False,
       False])

In [ ]:
#only those elements that will satisfy my condition ---> filtering

less_than_500= costs_cleaned[costs_cleaned < 500]

In [ ]:
less_than_500

array([300.])

In [ ]:
costs_cleaned

array([800., 800., 800., 300., 600., 600., 600., 700., 550., 500.])